language: java
jdk:
- openjdk6
install: "./gradlew setupCiWorkspace -S"
script: "./gradlew build"
env:
  global: TERM=dumb
deploy:
  provider: releases
  api_key:
    secure: QtzbYIHQOfWwxUUFyz5NnupXEpt6LBvRmVdaUIaJC7JWE084sBmllKXBY7nvFR56za29SiDpwlzvxXxd8rO//sZ+uHQlceCitLV0BIBy0OvH6aOqaLpXbTkHyNelsRPQT6rtzHh5TMh3eb4tM9L8IDF4HrmM5R8ml1w6WoK1hHITbCoa71747Pj8mVyVNcVDTVvy/Bm3LdnuLY01z5xUU1romqgi6NDeqIDYXWb9l02Ats11T6fz78EPTO6DBiC8RsvWAlDgM144qaqHFMSa0YaVJQ8t+ESFk4tca0xiYu59uYo3AtPc7p8R/RBQFknFBqf3w6vfMGWnzIxYeVRXUqTz3fHOvcLgWhItlm5MO0CWInYJx9nMfvzi8oTkmZs3qNxnFtYk9mAT6CULrx3eBOV6mpaorcvtFJXUsCukExFCtb1fMOosYHJsfTMwz9hecJCdD0stTS9aWYJAFKVaEhzL4CtvLYCdjeAlczUT9mq7T9Hk5x9CB6iTnOdS0lYcu6hpBneQqF6gIjPM3m55xdQVPL+HgOIxyTCw6qU8AcqvMycItQs359o7l1dsmMFZZetcLAn1dUeRwN0VphJxUFIMWml/9YbZ3OKXX1AN1KNgyyX+tdxPcv20WKdGHOlwhEFDwLRSovS7JvABWWhvDASlHN45ckBDp1/NxdZRaJQ=
  file: ".travis.yml"
  on:
    repo: supertassu/PowerCraft
